name: CI-CD-Multibuild

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: ECR Login
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Services
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          declare -A SERVICES
          SERVICES["queue-api"]="./queue/queue-api/Dockerfile ./queue"
          SERVICES["queue-manager"]="./queue/queue-manager/Dockerfile ./queue"
          SERVICES["chat-server"]="./chat-server/Dockerfile ./chat-server" 
          TAG="${COMMIT_SHA::7}"

          for SERVICE in "${!SERVICES[@]}"; do
            FILE_AND_CONTEXT=${SERVICES[$SERVICE]}
            DOCKERFILE=$(echo $FILE_AND_CONTEXT | awk '{print $1}')
            CONTEXT=$(echo $FILE_AND_CONTEXT | awk '{print $2}')
            IMAGE="$REGISTRY/$SERVICE:$TAG"

            echo "==============================="
            echo "Building $SERVICE with tag $TAG..."
            echo "==============================="

            docker build -t $IMAGE -f $DOCKERFILE $CONTEXT

            echo "Pushing $SERVICE â†’ $IMAGE ..."
            docker push $IMAGE
            
            docker tag $IMAGE "$REGISTRY/$SERVICE:latest"
            docker push "$REGISTRY/$SERVICE:latest"
          done

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name ${{ secrets.K8S_CLUSTER_NAME }} \
            --region ${{ secrets.AWS_REGION }}

      - name: Update EKS Deployments
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          SERVICES="queue-api queue-manager chat-server" 
          TAG="${COMMIT_SHA::7}"

          for SERVICE in $SERVICES; do
            IMAGE="$REGISTRY/$SERVICE:$TAG"

            echo "Updating Deployment for $SERVICE to image tag $TAG in queue-system..."
            
            kubectl set image deployment/$SERVICE $SERVICE=$IMAGE -n queue-system
            
            echo "Waiting for rollout status of $SERVICE ..."
 
            kubectl rollout status deployment/$SERVICE -n queue-system --timeout=5m
          done
