name: MonoRepo ECR & EKS CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - { name: "queue-api", path: "queue/queue-api", image: "queue-api" }
          - { name: "queue-manager", path: "queue/queue-manager", image: "queue-manager" }
          - { name: "chat-server", path: "chat-server", image: "chat-server" }

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

   
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

     
      - name: Ensure ECR repository exists
        run: |
          REPO=${{ matrix.service.image }}
          aws ecr describe-repositories --repository-names $REPO || \
          aws ecr create-repository --repository-name $REPO

   
      - name: Build and Push Docker image
        run: |
          IMAGE="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ matrix.service.image }}:latest"

          echo "Building $IMAGE using context: ./${{ matrix.service.path }}"
          docker build -t $IMAGE ./${{ matrix.service.path }}

          echo "Pushing $IMAGE"
          docker push $IMAGE

   
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

     
      - name: Update EKS Deployment image
        run: |
          IMAGE="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ matrix.service.image }}:latest"

          echo "Updating deployment: ${{ matrix.service.name }}"

          kubectl set image deployment/${{ matrix.service.name }} \
            ${{ matrix.service.name }}=$IMAGE

          kubectl rollout status deployment/${{ matrix.service.name }}
